#!/usr/bin/env bash

set -euxo pipefail
export FDB_VERSION=${FDB_VERSION:-'6.2.28'}

# Workaround for never Ubuntu/Debian releases which doesn't contain the GeTrust CA anymore
mkdir -p /usr/local/share/ca-certificates
cp ./foundationdb-kubernetes-sidecar/files/GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/GeoTrust_Global_CA.crt
update-ca-certificates

# Required for Windows cross-compile
apt-get update && apt-get install -y gcc-multilib gcc-mingw-w64

# Install the Ubtunu packahe
curl --fail -o fdb.deb "https://www.foundationdb.org/downloads/${FDB_VERSION}/ubuntu/installers/foundationdb-clients_${FDB_VERSION}-1_amd64.deb"
dpkg -i fdb.deb
