name: Release kubectl plugin
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64
        goos: ["linux", "windows", "darwin"]
        goarch: ["amd64"]
    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          curl --fail https://www.foundationdb.org/downloads/6.2.28/ubuntu/installers/foundationdb-clients_6.2.28-1_amd64.deb -o fdb.deb
          sudo dpkg -i fdb.deb
      - uses: wangyoucao577/go-release-action@v1.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz"
          project_path: "./kubectl-fdb"
          binary_name: "kubectl-fdb"
